[package]
name = "huffman_encoding"
version = "0.4.0"
edition = "2024"

[dependencies]
bit_writer_reader = {git = "https://github.com/Strilets-Glib-FI41mn/Information_Transformation_Algorithms_Task02", tag = "0.4.0"}

[features]
draw = []
print_converter = []